version: '3.9'

services:

  db:
    image: mysql:8.0
    platform: $PLATFORM
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network


  wordpress:
    depends_on:
      - db
    image: wordpress:6.2.0-php8.2-fpm-alpine
    platform: $PLATFORM
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
          define('WP_HOME', '$WP_HOME' );
          define('WP_SITEURL', '$WP_SITEURL' );
    volumes:
      - wordpress:/var/www/html
      - ${PWD}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - app-network

  webserver_dev:
    depends_on:
      - db
    image: nginx:1.23.4-alpine
    platform: $PLATFORM
    profiles: ['webserver_dev']
    container_name: webserver_dev
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf-dev:/etc/nginx/conf.d
    networks:
      - app-network


  webserver_live:
    depends_on:
      - db
    image: nginx:1.23.4-alpine
    platform: $PLATFORM
    profiles: ['webserver_live']
    container_name: webserver_live
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf-live:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge

