version: '3.9'

services:

  # ╭──────────────────────────────────────────────────────────╮
  # │                         DATABASE                         │
  # ╰──────────────────────────────────────────────────────────╯
  storelondonparkour_mariadb:
    image: mariadb:10.6.13-focal
    platform: $PLATFORM
    container_name: storelondonparkour_mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$DATABASE_NAME
    volumes:
      - db-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - store-londonparkour


  # ╭──────────────────────────────────────────────────────────╮
  # │                     PHP + WORDPRESS                      │
  # ╰──────────────────────────────────────────────────────────╯
  wordpress:
    depends_on:
      - storelondonparkour_mariadb
    image: wordpress:6.2.0-php8.2-fpm-alpine
    platform: $PLATFORM
    container_name: storelondonparkour_wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: storelondonparkour_mariadb:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $DATABASE_NAME
      WORDPRESS_CONFIG_EXTRA: |
          define('WP_HOME', '$WP_HOME' );
          define('WP_SITEURL', '$WP_SITEURL' );
    volumes:
      - website-data:/var/www/html
      - ${PWD}/config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - store-londonparkour

  # ╭──────────────────────────────────────────────────────────╮
  # │                          NGINX                           │
  # │                     Developer & Live                     │
  # ╰──────────────────────────────────────────────────────────╯
  storelondonparkour_webserver_dev:
    depends_on:
      - storelondonparkour_mariadb
    image: nginx:1.23.4-alpine
    platform: $PLATFORM
    profiles: ['dev']
    container_name: storelondonparkour_webserver_dev
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - website-data:/var/www/html
      - ${PWD}/config/nginx/nginx-conf-dev:/etc/nginx/conf.d
    networks:
      store-londonparkour:
        aliases:
          - store.londonparkour.com
          - www.store.londonparkour.com
          - localhost


  storelondonparkour_webserver_live:
    depends_on:
      - storelondonparkour_wordpress
    image: nginx:1.23.4-alpine
    platform: $PLATFORM
    profiles: ['live']
    container_name: storelondonparkour_webserver_live
    restart: unless-stopped
    ports:
      - "2080:80"
      - "20443:443"
    volumes:
      - website-data:/var/www/html
      - ${PWD}/config/nginx/nginx-conf-live:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      store-londonparkour:
        aliases:
          - store.londonparkour.com
          - www.store.londonparkour.com
          - localhost

  # ╭──────────────────────────────────────────────────────────╮
  # │                         CERTBOT                          │
  # ╰──────────────────────────────────────────────────────────╯
  # storelondonparkour_certbot:
  #   depends_on:
  #     - storelondonparkour_webserver_live
  #   image: certbot/certbot
  #   profiles: ['live']
  #   container_name: storelondonparkour_certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - website-data:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email $CERTBOT_EMAIL --agree-tos --no-eff-email --$CERTBOT_FLAG -d $CERTBOT_DOMAIN -d startparkour.com 

  
volumes:
  certbot-etc:
  website-data:
  db-data:

networks:
  store-londonparkour:
    driver: bridge