version: '3.9'

services:

  db:
    image: mariadb:10.7.8
    platform: $PLATFORM
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mariadb
    networks:
      - app-network


  wordpress:
    depends_on:
      - db
    image: wordpress:6.2.0-php8.2-fpm-alpine
    platform: $PLATFORM
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MARIADB_USER
      WORDPRESS_DB_PASSWORD: $MARIADB_PASSWORD
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
          define('WP_HOME', '$WP_HOME' );
          define('WP_SITEURL', '$WP_SITEURL' );
    volumes:
      - wordpress:/var/www/html
      - ${PWD}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - app-network

  webserver_dev:
    depends_on:
      - db
    image: nginx:1.23.4-alpine
    platform: $PLATFORM
    profiles: ['dev']
    container_name: webserver_dev
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf-dev:/etc/nginx/conf.d
    networks:
      - app-network


  webserver_live:
    depends_on:
      - wordpress
    image: nginx:1.23.4-alpine
    platform: $PLATFORM
    profiles: ['live']
    container_name: webserver_live
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf-live:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver_live
    image: certbot/certbot
    profiles: ['live']
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email $CERTBOT_EMAIL --agree-tos --no-eff-email --$CERTBOT_FLAG -d $CERTBOT_DOMAIN -d www.$CERTBOT_DOMAIN -d test.$CERTBOT_DOMAIN

  
volumes:
  certbot-etc:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge

